// react-app/src/App/Visualization/LineChart/Marker/index.js
import React, {useEffect, useRef} from 'react';
import {select} from "d3-selection";
import 'd3-transition';
import {DURATION} from "../../../../constant";

const Marker = ({item}) => {
    const markerRef = useRef(null);

    useEffect(() => {
        select(markerRef.current)
            .transition()
            .duration(DURATION)
            .attr("cy", item.y);
    });

    return (
        <circle className="marker" ref={markerRef} r={10} cx={item.x} cy={item.startingY}/>
    )
};
export default Marker;

// angular-app/src/app/visualization/line-chart/marker/marker.component.ts
import { Component, Input } from '@angular/core';
import { DURATION } from '../../../../lib/constant';

export interface MarkerItem {
  x: number,
  y: number,
  startingY: number
}

@Component({
  selector: '[app-marker]',
  templateUrl: './marker.component.html'
})
export class MarkerComponent {
  @Input() item: MarkerItem;
  protected transition = t => t.duration(DURATION);
}

<svg:circle class="marker" [attr.r.px]="10"
            [attr.cx.px]="item.x"
            [attr.cy.px]="item.startingY"
            [appSvgTransition]="transition"
            [d3-attr]="{cy: item.y}">
</svg:circle>
